#!/bin/bash

# Update the ending copyright year of Forlan in the *.template files

if [[ $# != 1 || $1 != [0-9][0-9][0-9][0-9] ]];
then echo usage $0 DDDD;
     exit 1;
fi;

newyear=$1

tmpfile=change-copyright.tmp.$$

function processfile ()
{
  sed "s/Copyright &copy; ..../Copyright \&copy; $newyear/" \
    $1 > $tmpfile;
  mv $tmpfile $1;
}

for file in *.template;
do processfile $file;
done;
