# Generated makefile
#

MLDOC_BIN = /usr/local/bin

EXTRACT_INFO = $(MLDOC_BIN)/extract-info
HTML_GEN = $(MLDOC_BIN)/html-gen
HTML_INDEX = $(MLDOC_BIN)/html-index
HTML_TOC = $(MLDOC_BIN)/html-toc
LATEX_GEN = $(MLDOC_BIN)/latex-gen
MERGE_INFO = $(MLDOC_BIN)/merge-info
PROOF_LATEX = $(MLDOC_BIN)/proof-latex
RUN_LATEX = $(MLDOC_BIN)/run-latex
DVIPS = dvips

SRC_DIR = ML-Doc
INFO_DIR = Info
HTML_DIR = HTML
LATEX_DIR = Hardcopy
PROOF_DIR = Proof

CONFIG = Config.cfg CATALOG
HTML_INFO = $(CONFIG) $(INFO_DIR)/HTML.info
LATEX_INFO = $(CONFIG) $(INFO_DIR)/LaTeX.info

HTML_INFO_FILES =	$(INFO_DIR)/auxiliary-subsect.info \
	$(INFO_DIR)/debug.info \
	$(INFO_DIR)/dfa.info \
	$(INFO_DIR)/efa.info \
	$(INFO_DIR)/fa.info \
	$(INFO_DIR)/gram-subsect.info \
	$(INFO_DIR)/gram.info \
	$(INFO_DIR)/index.info \
	$(INFO_DIR)/lex-subsect.info \
	$(INFO_DIR)/lex.info \
	$(INFO_DIR)/list-aux.info \
	$(INFO_DIR)/lp.info \
	$(INFO_DIR)/messages.info \
	$(INFO_DIR)/nfa.info \
	$(INFO_DIR)/params.info \
	$(INFO_DIR)/pp.info \
	$(INFO_DIR)/prod-set.info \
	$(INFO_DIR)/prod.info \
	$(INFO_DIR)/prog-subsect.info \
	$(INFO_DIR)/prog.info \
	$(INFO_DIR)/pt.info \
	$(INFO_DIR)/reg-fa-subsect.info \
	$(INFO_DIR)/reg.info \
	$(INFO_DIR)/rel.info \
	$(INFO_DIR)/rfa.info \
	$(INFO_DIR)/set.info \
	$(INFO_DIR)/sort-set-rel-tab-subsect.info \
	$(INFO_DIR)/sort.info \
	$(INFO_DIR)/str-set.info \
	$(INFO_DIR)/str.info \
	$(INFO_DIR)/string-aux.info \
	$(INFO_DIR)/sym-rel.info \
	$(INFO_DIR)/sym-set.info \
	$(INFO_DIR)/sym-str-subsect.info \
	$(INFO_DIR)/sym.info \
	$(INFO_DIR)/system.info \
	$(INFO_DIR)/tab.info \
	$(INFO_DIR)/top-level-subsect.info \
	$(INFO_DIR)/tran-reg-set.info \
	$(INFO_DIR)/tran-reg.info \
	$(INFO_DIR)/tran-set.info \
	$(INFO_DIR)/tran.info \
	$(INFO_DIR)/use.info \
	$(INFO_DIR)/utility-subsect.info \
	$(INFO_DIR)/var-set.info \
	$(INFO_DIR)/var.info \
	$(INFO_DIR)/version.info

LATEX_INFO_FILES =	$(INFO_DIR)/auxiliary-subsect.info \
	$(INFO_DIR)/debug.info \
	$(INFO_DIR)/dfa.info \
	$(INFO_DIR)/efa.info \
	$(INFO_DIR)/fa.info \
	$(INFO_DIR)/gram-subsect.info \
	$(INFO_DIR)/gram.info \
	$(INFO_DIR)/index.info \
	$(INFO_DIR)/lex-subsect.info \
	$(INFO_DIR)/lex.info \
	$(INFO_DIR)/list-aux.info \
	$(INFO_DIR)/lp.info \
	$(INFO_DIR)/messages.info \
	$(INFO_DIR)/nfa.info \
	$(INFO_DIR)/params.info \
	$(INFO_DIR)/pp.info \
	$(INFO_DIR)/prod-set.info \
	$(INFO_DIR)/prod.info \
	$(INFO_DIR)/prog-subsect.info \
	$(INFO_DIR)/prog.info \
	$(INFO_DIR)/pt.info \
	$(INFO_DIR)/reg-fa-subsect.info \
	$(INFO_DIR)/reg.info \
	$(INFO_DIR)/rel.info \
	$(INFO_DIR)/rfa.info \
	$(INFO_DIR)/set.info \
	$(INFO_DIR)/sort-set-rel-tab-subsect.info \
	$(INFO_DIR)/sort.info \
	$(INFO_DIR)/str-set.info \
	$(INFO_DIR)/str.info \
	$(INFO_DIR)/string-aux.info \
	$(INFO_DIR)/sym-rel.info \
	$(INFO_DIR)/sym-set.info \
	$(INFO_DIR)/sym-str-subsect.info \
	$(INFO_DIR)/sym.info \
	$(INFO_DIR)/system.info \
	$(INFO_DIR)/tab.info \
	$(INFO_DIR)/top-level-subsect.info \
	$(INFO_DIR)/tran-reg-set.info \
	$(INFO_DIR)/tran-reg.info \
	$(INFO_DIR)/tran-set.info \
	$(INFO_DIR)/tran.info \
	$(INFO_DIR)/use.info \
	$(INFO_DIR)/utility-subsect.info \
	$(INFO_DIR)/var-set.info \
	$(INFO_DIR)/var.info \
	$(INFO_DIR)/version.info

HTML_FILES =	$(HTML_DIR)/index-all.html \
	$(HTML_DIR)/toc.html \
	$(HTML_DIR)/auxiliary-subsect.html \
	$(HTML_DIR)/debug.html \
	$(HTML_DIR)/dfa.html \
	$(HTML_DIR)/efa.html \
	$(HTML_DIR)/fa.html \
	$(HTML_DIR)/gram-subsect.html \
	$(HTML_DIR)/gram.html \
	$(HTML_DIR)/index.html \
	$(HTML_DIR)/lex-subsect.html \
	$(HTML_DIR)/lex.html \
	$(HTML_DIR)/list-aux.html \
	$(HTML_DIR)/lp.html \
	$(HTML_DIR)/messages.html \
	$(HTML_DIR)/nfa.html \
	$(HTML_DIR)/params.html \
	$(HTML_DIR)/pp.html \
	$(HTML_DIR)/prod-set.html \
	$(HTML_DIR)/prod.html \
	$(HTML_DIR)/prog-subsect.html \
	$(HTML_DIR)/prog.html \
	$(HTML_DIR)/pt.html \
	$(HTML_DIR)/reg-fa-subsect.html \
	$(HTML_DIR)/reg.html \
	$(HTML_DIR)/rel.html \
	$(HTML_DIR)/rfa.html \
	$(HTML_DIR)/set.html \
	$(HTML_DIR)/sort-set-rel-tab-subsect.html \
	$(HTML_DIR)/sort.html \
	$(HTML_DIR)/str-set.html \
	$(HTML_DIR)/str.html \
	$(HTML_DIR)/string-aux.html \
	$(HTML_DIR)/sym-rel.html \
	$(HTML_DIR)/sym-set.html \
	$(HTML_DIR)/sym-str-subsect.html \
	$(HTML_DIR)/sym.html \
	$(HTML_DIR)/system.html \
	$(HTML_DIR)/tab.html \
	$(HTML_DIR)/top-level-subsect.html \
	$(HTML_DIR)/tran-reg-set.html \
	$(HTML_DIR)/tran-reg.html \
	$(HTML_DIR)/tran-set.html \
	$(HTML_DIR)/tran.html \
	$(HTML_DIR)/use.html \
	$(HTML_DIR)/utility-subsect.html \
	$(HTML_DIR)/var-set.html \
	$(HTML_DIR)/var.html \
	$(HTML_DIR)/version.html

LATEX_FILES =	$(LATEX_DIR)/auxiliary-subsect.tex \
	$(LATEX_DIR)/debug.tex \
	$(LATEX_DIR)/dfa.tex \
	$(LATEX_DIR)/efa.tex \
	$(LATEX_DIR)/fa.tex \
	$(LATEX_DIR)/gram-subsect.tex \
	$(LATEX_DIR)/gram.tex \
	$(LATEX_DIR)/index.tex \
	$(LATEX_DIR)/lex-subsect.tex \
	$(LATEX_DIR)/lex.tex \
	$(LATEX_DIR)/list-aux.tex \
	$(LATEX_DIR)/lp.tex \
	$(LATEX_DIR)/messages.tex \
	$(LATEX_DIR)/nfa.tex \
	$(LATEX_DIR)/params.tex \
	$(LATEX_DIR)/pp.tex \
	$(LATEX_DIR)/prod-set.tex \
	$(LATEX_DIR)/prod.tex \
	$(LATEX_DIR)/prog-subsect.tex \
	$(LATEX_DIR)/prog.tex \
	$(LATEX_DIR)/pt.tex \
	$(LATEX_DIR)/reg-fa-subsect.tex \
	$(LATEX_DIR)/reg.tex \
	$(LATEX_DIR)/rel.tex \
	$(LATEX_DIR)/rfa.tex \
	$(LATEX_DIR)/set.tex \
	$(LATEX_DIR)/sort-set-rel-tab-subsect.tex \
	$(LATEX_DIR)/sort.tex \
	$(LATEX_DIR)/str-set.tex \
	$(LATEX_DIR)/str.tex \
	$(LATEX_DIR)/string-aux.tex \
	$(LATEX_DIR)/sym-rel.tex \
	$(LATEX_DIR)/sym-set.tex \
	$(LATEX_DIR)/sym-str-subsect.tex \
	$(LATEX_DIR)/sym.tex \
	$(LATEX_DIR)/system.tex \
	$(LATEX_DIR)/tab.tex \
	$(LATEX_DIR)/top-level-subsect.tex \
	$(LATEX_DIR)/tran-reg-set.tex \
	$(LATEX_DIR)/tran-reg.tex \
	$(LATEX_DIR)/tran-set.tex \
	$(LATEX_DIR)/tran.tex \
	$(LATEX_DIR)/use.tex \
	$(LATEX_DIR)/utility-subsect.tex \
	$(LATEX_DIR)/var-set.tex \
	$(LATEX_DIR)/var.tex \
	$(LATEX_DIR)/version.tex

PROOF_FILES =	$(PROOF_DIR)/auxiliary-subsect.tex \
	$(PROOF_DIR)/debug.tex \
	$(PROOF_DIR)/dfa.tex \
	$(PROOF_DIR)/efa.tex \
	$(PROOF_DIR)/fa.tex \
	$(PROOF_DIR)/gram-subsect.tex \
	$(PROOF_DIR)/gram.tex \
	$(PROOF_DIR)/index.tex \
	$(PROOF_DIR)/lex-subsect.tex \
	$(PROOF_DIR)/lex.tex \
	$(PROOF_DIR)/list-aux.tex \
	$(PROOF_DIR)/lp.tex \
	$(PROOF_DIR)/messages.tex \
	$(PROOF_DIR)/nfa.tex \
	$(PROOF_DIR)/params.tex \
	$(PROOF_DIR)/pp.tex \
	$(PROOF_DIR)/prod-set.tex \
	$(PROOF_DIR)/prod.tex \
	$(PROOF_DIR)/prog-subsect.tex \
	$(PROOF_DIR)/prog.tex \
	$(PROOF_DIR)/pt.tex \
	$(PROOF_DIR)/reg-fa-subsect.tex \
	$(PROOF_DIR)/reg.tex \
	$(PROOF_DIR)/rel.tex \
	$(PROOF_DIR)/rfa.tex \
	$(PROOF_DIR)/set.tex \
	$(PROOF_DIR)/sort-set-rel-tab-subsect.tex \
	$(PROOF_DIR)/sort.tex \
	$(PROOF_DIR)/str-set.tex \
	$(PROOF_DIR)/str.tex \
	$(PROOF_DIR)/string-aux.tex \
	$(PROOF_DIR)/sym-rel.tex \
	$(PROOF_DIR)/sym-set.tex \
	$(PROOF_DIR)/sym-str-subsect.tex \
	$(PROOF_DIR)/sym.tex \
	$(PROOF_DIR)/system.tex \
	$(PROOF_DIR)/tab.tex \
	$(PROOF_DIR)/top-level-subsect.tex \
	$(PROOF_DIR)/tran-reg-set.tex \
	$(PROOF_DIR)/tran-reg.tex \
	$(PROOF_DIR)/tran-set.tex \
	$(PROOF_DIR)/tran.tex \
	$(PROOF_DIR)/use.tex \
	$(PROOF_DIR)/utility-subsect.tex \
	$(PROOF_DIR)/var-set.tex \
	$(PROOF_DIR)/var.tex \
	$(PROOF_DIR)/version.tex

HTML:	$(HTML_FILES)

$(HTML_DIR)/toc.html:	$(HTML_INFO) toc.template
	$(HTML_TOC)

$(HTML_DIR)/index-all.html:	$(HTML_INFO) index.template
	$(HTML_INDEX) -all

$(HTML_DIR)/auxiliary-subsect.html:	$(SRC_DIR)/auxiliary-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/auxiliary-subsect.mldoc

$(HTML_DIR)/debug.html:	$(SRC_DIR)/debug.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/debug.mldoc

$(HTML_DIR)/dfa.html:	$(SRC_DIR)/dfa.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/dfa.mldoc

$(HTML_DIR)/efa.html:	$(SRC_DIR)/efa.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/efa.mldoc

$(HTML_DIR)/fa.html:	$(SRC_DIR)/fa.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/fa.mldoc

$(HTML_DIR)/gram-subsect.html:	$(SRC_DIR)/gram-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/gram-subsect.mldoc

$(HTML_DIR)/gram.html:	$(SRC_DIR)/gram.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/gram.mldoc

$(HTML_DIR)/index.html:	$(SRC_DIR)/index.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/index.mldoc

$(HTML_DIR)/lex-subsect.html:	$(SRC_DIR)/lex-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/lex-subsect.mldoc

$(HTML_DIR)/lex.html:	$(SRC_DIR)/lex.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/lex.mldoc

$(HTML_DIR)/list-aux.html:	$(SRC_DIR)/list-aux.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/list-aux.mldoc

$(HTML_DIR)/lp.html:	$(SRC_DIR)/lp.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/lp.mldoc

$(HTML_DIR)/messages.html:	$(SRC_DIR)/messages.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/messages.mldoc

$(HTML_DIR)/nfa.html:	$(SRC_DIR)/nfa.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/nfa.mldoc

$(HTML_DIR)/params.html:	$(SRC_DIR)/params.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/params.mldoc

$(HTML_DIR)/pp.html:	$(SRC_DIR)/pp.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/pp.mldoc

$(HTML_DIR)/prod-set.html:	$(SRC_DIR)/prod-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/prod-set.mldoc

$(HTML_DIR)/prod.html:	$(SRC_DIR)/prod.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/prod.mldoc

$(HTML_DIR)/prog-subsect.html:	$(SRC_DIR)/prog-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/prog-subsect.mldoc

$(HTML_DIR)/prog.html:	$(SRC_DIR)/prog.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/prog.mldoc

$(HTML_DIR)/pt.html:	$(SRC_DIR)/pt.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/pt.mldoc

$(HTML_DIR)/reg-fa-subsect.html:	$(SRC_DIR)/reg-fa-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/reg-fa-subsect.mldoc

$(HTML_DIR)/reg.html:	$(SRC_DIR)/reg.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/reg.mldoc

$(HTML_DIR)/rel.html:	$(SRC_DIR)/rel.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/rel.mldoc

$(HTML_DIR)/rfa.html:	$(SRC_DIR)/rfa.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/rfa.mldoc

$(HTML_DIR)/set.html:	$(SRC_DIR)/set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/set.mldoc

$(HTML_DIR)/sort-set-rel-tab-subsect.html:	$(SRC_DIR)/sort-set-rel-tab-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/sort-set-rel-tab-subsect.mldoc

$(HTML_DIR)/sort.html:	$(SRC_DIR)/sort.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/sort.mldoc

$(HTML_DIR)/str-set.html:	$(SRC_DIR)/str-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/str-set.mldoc

$(HTML_DIR)/str.html:	$(SRC_DIR)/str.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/str.mldoc

$(HTML_DIR)/string-aux.html:	$(SRC_DIR)/string-aux.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/string-aux.mldoc

$(HTML_DIR)/sym-rel.html:	$(SRC_DIR)/sym-rel.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/sym-rel.mldoc

$(HTML_DIR)/sym-set.html:	$(SRC_DIR)/sym-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/sym-set.mldoc

$(HTML_DIR)/sym-str-subsect.html:	$(SRC_DIR)/sym-str-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/sym-str-subsect.mldoc

$(HTML_DIR)/sym.html:	$(SRC_DIR)/sym.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/sym.mldoc

$(HTML_DIR)/system.html:	$(SRC_DIR)/system.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/system.mldoc

$(HTML_DIR)/tab.html:	$(SRC_DIR)/tab.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/tab.mldoc

$(HTML_DIR)/top-level-subsect.html:	$(SRC_DIR)/top-level-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/top-level-subsect.mldoc

$(HTML_DIR)/tran-reg-set.html:	$(SRC_DIR)/tran-reg-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/tran-reg-set.mldoc

$(HTML_DIR)/tran-reg.html:	$(SRC_DIR)/tran-reg.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/tran-reg.mldoc

$(HTML_DIR)/tran-set.html:	$(SRC_DIR)/tran-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/tran-set.mldoc

$(HTML_DIR)/tran.html:	$(SRC_DIR)/tran.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/tran.mldoc

$(HTML_DIR)/use.html:	$(SRC_DIR)/use.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/use.mldoc

$(HTML_DIR)/utility-subsect.html:	$(SRC_DIR)/utility-subsect.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/utility-subsect.mldoc

$(HTML_DIR)/var-set.html:	$(SRC_DIR)/var-set.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/var-set.mldoc

$(HTML_DIR)/var.html:	$(SRC_DIR)/var.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/var.mldoc

$(HTML_DIR)/version.html:	$(SRC_DIR)/version.mldoc $(HTML_INFO) page.template
	$(HTML_GEN) $(SRC_DIR)/version.mldoc

$(INFO_DIR)/HTML.info:	$(HTML_INFO_FILES)
	$(MERGE_INFO) -o $(INFO_DIR)/HTML.info $(HTML_INFO_FILES)

$(INFO_DIR)/LaTeX.info:	$(LATEX_INFO_FILES)
	$(MERGE_INFO) -o $(INFO_DIR)/LaTeX.info $(LATEX_INFO_FILES)

$(INFO_DIR)/auxiliary-subsect.info:	$(SRC_DIR)/auxiliary-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/auxiliary-subsect.mldoc

$(INFO_DIR)/debug.info:	$(SRC_DIR)/debug.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/debug.mldoc

$(INFO_DIR)/dfa.info:	$(SRC_DIR)/dfa.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/dfa.mldoc

$(INFO_DIR)/efa.info:	$(SRC_DIR)/efa.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/efa.mldoc

$(INFO_DIR)/fa.info:	$(SRC_DIR)/fa.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/fa.mldoc

$(INFO_DIR)/gram-subsect.info:	$(SRC_DIR)/gram-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/gram-subsect.mldoc

$(INFO_DIR)/gram.info:	$(SRC_DIR)/gram.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/gram.mldoc

$(INFO_DIR)/index.info:	$(SRC_DIR)/index.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/index.mldoc

$(INFO_DIR)/lex-subsect.info:	$(SRC_DIR)/lex-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/lex-subsect.mldoc

$(INFO_DIR)/lex.info:	$(SRC_DIR)/lex.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/lex.mldoc

$(INFO_DIR)/list-aux.info:	$(SRC_DIR)/list-aux.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/list-aux.mldoc

$(INFO_DIR)/lp.info:	$(SRC_DIR)/lp.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/lp.mldoc

$(INFO_DIR)/messages.info:	$(SRC_DIR)/messages.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/messages.mldoc

$(INFO_DIR)/nfa.info:	$(SRC_DIR)/nfa.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/nfa.mldoc

$(INFO_DIR)/params.info:	$(SRC_DIR)/params.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/params.mldoc

$(INFO_DIR)/pp.info:	$(SRC_DIR)/pp.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/pp.mldoc

$(INFO_DIR)/prod-set.info:	$(SRC_DIR)/prod-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/prod-set.mldoc

$(INFO_DIR)/prod.info:	$(SRC_DIR)/prod.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/prod.mldoc

$(INFO_DIR)/prog-subsect.info:	$(SRC_DIR)/prog-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/prog-subsect.mldoc

$(INFO_DIR)/prog.info:	$(SRC_DIR)/prog.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/prog.mldoc

$(INFO_DIR)/pt.info:	$(SRC_DIR)/pt.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/pt.mldoc

$(INFO_DIR)/reg-fa-subsect.info:	$(SRC_DIR)/reg-fa-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/reg-fa-subsect.mldoc

$(INFO_DIR)/reg.info:	$(SRC_DIR)/reg.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/reg.mldoc

$(INFO_DIR)/rel.info:	$(SRC_DIR)/rel.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/rel.mldoc

$(INFO_DIR)/rfa.info:	$(SRC_DIR)/rfa.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/rfa.mldoc

$(INFO_DIR)/set.info:	$(SRC_DIR)/set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/set.mldoc

$(INFO_DIR)/sort-set-rel-tab-subsect.info:	$(SRC_DIR)/sort-set-rel-tab-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/sort-set-rel-tab-subsect.mldoc

$(INFO_DIR)/sort.info:	$(SRC_DIR)/sort.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/sort.mldoc

$(INFO_DIR)/str-set.info:	$(SRC_DIR)/str-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/str-set.mldoc

$(INFO_DIR)/str.info:	$(SRC_DIR)/str.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/str.mldoc

$(INFO_DIR)/string-aux.info:	$(SRC_DIR)/string-aux.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/string-aux.mldoc

$(INFO_DIR)/sym-rel.info:	$(SRC_DIR)/sym-rel.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/sym-rel.mldoc

$(INFO_DIR)/sym-set.info:	$(SRC_DIR)/sym-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/sym-set.mldoc

$(INFO_DIR)/sym-str-subsect.info:	$(SRC_DIR)/sym-str-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/sym-str-subsect.mldoc

$(INFO_DIR)/sym.info:	$(SRC_DIR)/sym.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/sym.mldoc

$(INFO_DIR)/system.info:	$(SRC_DIR)/system.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/system.mldoc

$(INFO_DIR)/tab.info:	$(SRC_DIR)/tab.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/tab.mldoc

$(INFO_DIR)/top-level-subsect.info:	$(SRC_DIR)/top-level-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/top-level-subsect.mldoc

$(INFO_DIR)/tran-reg-set.info:	$(SRC_DIR)/tran-reg-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/tran-reg-set.mldoc

$(INFO_DIR)/tran-reg.info:	$(SRC_DIR)/tran-reg.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/tran-reg.mldoc

$(INFO_DIR)/tran-set.info:	$(SRC_DIR)/tran-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/tran-set.mldoc

$(INFO_DIR)/tran.info:	$(SRC_DIR)/tran.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/tran.mldoc

$(INFO_DIR)/use.info:	$(SRC_DIR)/use.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/use.mldoc

$(INFO_DIR)/utility-subsect.info:	$(SRC_DIR)/utility-subsect.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/utility-subsect.mldoc

$(INFO_DIR)/var-set.info:	$(SRC_DIR)/var-set.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/var-set.mldoc

$(INFO_DIR)/var.info:	$(SRC_DIR)/var.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/var.mldoc

$(INFO_DIR)/version.info:	$(SRC_DIR)/version.mldoc $(CONFIG)
	$(EXTRACT_INFO) $(SRC_DIR)/version.mldoc

Hardcopy:	$(LATEX_FILES)

$(LATEX_DIR)/auxiliary-subsect.tex:	$(SRC_DIR)/auxiliary-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/auxiliary-subsect.mldoc

$(LATEX_DIR)/debug.tex:	$(SRC_DIR)/debug.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/debug.mldoc

$(LATEX_DIR)/dfa.tex:	$(SRC_DIR)/dfa.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/dfa.mldoc

$(LATEX_DIR)/efa.tex:	$(SRC_DIR)/efa.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/efa.mldoc

$(LATEX_DIR)/fa.tex:	$(SRC_DIR)/fa.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/fa.mldoc

$(LATEX_DIR)/gram-subsect.tex:	$(SRC_DIR)/gram-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/gram-subsect.mldoc

$(LATEX_DIR)/gram.tex:	$(SRC_DIR)/gram.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/gram.mldoc

$(LATEX_DIR)/index.tex:	$(SRC_DIR)/index.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/index.mldoc

$(LATEX_DIR)/lex-subsect.tex:	$(SRC_DIR)/lex-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/lex-subsect.mldoc

$(LATEX_DIR)/lex.tex:	$(SRC_DIR)/lex.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/lex.mldoc

$(LATEX_DIR)/list-aux.tex:	$(SRC_DIR)/list-aux.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/list-aux.mldoc

$(LATEX_DIR)/lp.tex:	$(SRC_DIR)/lp.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/lp.mldoc

$(LATEX_DIR)/messages.tex:	$(SRC_DIR)/messages.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/messages.mldoc

$(LATEX_DIR)/nfa.tex:	$(SRC_DIR)/nfa.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/nfa.mldoc

$(LATEX_DIR)/params.tex:	$(SRC_DIR)/params.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/params.mldoc

$(LATEX_DIR)/pp.tex:	$(SRC_DIR)/pp.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/pp.mldoc

$(LATEX_DIR)/prod-set.tex:	$(SRC_DIR)/prod-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/prod-set.mldoc

$(LATEX_DIR)/prod.tex:	$(SRC_DIR)/prod.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/prod.mldoc

$(LATEX_DIR)/prog-subsect.tex:	$(SRC_DIR)/prog-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/prog-subsect.mldoc

$(LATEX_DIR)/prog.tex:	$(SRC_DIR)/prog.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/prog.mldoc

$(LATEX_DIR)/pt.tex:	$(SRC_DIR)/pt.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/pt.mldoc

$(LATEX_DIR)/reg-fa-subsect.tex:	$(SRC_DIR)/reg-fa-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/reg-fa-subsect.mldoc

$(LATEX_DIR)/reg.tex:	$(SRC_DIR)/reg.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/reg.mldoc

$(LATEX_DIR)/rel.tex:	$(SRC_DIR)/rel.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/rel.mldoc

$(LATEX_DIR)/rfa.tex:	$(SRC_DIR)/rfa.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/rfa.mldoc

$(LATEX_DIR)/set.tex:	$(SRC_DIR)/set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/set.mldoc

$(LATEX_DIR)/sort-set-rel-tab-subsect.tex:	$(SRC_DIR)/sort-set-rel-tab-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/sort-set-rel-tab-subsect.mldoc

$(LATEX_DIR)/sort.tex:	$(SRC_DIR)/sort.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/sort.mldoc

$(LATEX_DIR)/str-set.tex:	$(SRC_DIR)/str-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/str-set.mldoc

$(LATEX_DIR)/str.tex:	$(SRC_DIR)/str.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/str.mldoc

$(LATEX_DIR)/string-aux.tex:	$(SRC_DIR)/string-aux.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/string-aux.mldoc

$(LATEX_DIR)/sym-rel.tex:	$(SRC_DIR)/sym-rel.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/sym-rel.mldoc

$(LATEX_DIR)/sym-set.tex:	$(SRC_DIR)/sym-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/sym-set.mldoc

$(LATEX_DIR)/sym-str-subsect.tex:	$(SRC_DIR)/sym-str-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/sym-str-subsect.mldoc

$(LATEX_DIR)/sym.tex:	$(SRC_DIR)/sym.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/sym.mldoc

$(LATEX_DIR)/system.tex:	$(SRC_DIR)/system.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/system.mldoc

$(LATEX_DIR)/tab.tex:	$(SRC_DIR)/tab.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/tab.mldoc

$(LATEX_DIR)/top-level-subsect.tex:	$(SRC_DIR)/top-level-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/top-level-subsect.mldoc

$(LATEX_DIR)/tran-reg-set.tex:	$(SRC_DIR)/tran-reg-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/tran-reg-set.mldoc

$(LATEX_DIR)/tran-reg.tex:	$(SRC_DIR)/tran-reg.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/tran-reg.mldoc

$(LATEX_DIR)/tran-set.tex:	$(SRC_DIR)/tran-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/tran-set.mldoc

$(LATEX_DIR)/tran.tex:	$(SRC_DIR)/tran.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/tran.mldoc

$(LATEX_DIR)/use.tex:	$(SRC_DIR)/use.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/use.mldoc

$(LATEX_DIR)/utility-subsect.tex:	$(SRC_DIR)/utility-subsect.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/utility-subsect.mldoc

$(LATEX_DIR)/var-set.tex:	$(SRC_DIR)/var-set.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/var-set.mldoc

$(LATEX_DIR)/var.tex:	$(SRC_DIR)/var.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/var.mldoc

$(LATEX_DIR)/version.tex:	$(SRC_DIR)/version.mldoc $(LATEX_INFO)
	$(LATEX_GEN) $(SRC_DIR)/version.mldoc

Proof:	$(PROOF_FILES)

$(PROOF_DIR)/auxiliary-subsect.tex:	$(SRC_DIR)/auxiliary-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/auxiliary-subsect.mldoc

$(PROOF_DIR)/debug.tex:	$(SRC_DIR)/debug.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/debug.mldoc

$(PROOF_DIR)/dfa.tex:	$(SRC_DIR)/dfa.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/dfa.mldoc

$(PROOF_DIR)/efa.tex:	$(SRC_DIR)/efa.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/efa.mldoc

$(PROOF_DIR)/fa.tex:	$(SRC_DIR)/fa.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/fa.mldoc

$(PROOF_DIR)/gram-subsect.tex:	$(SRC_DIR)/gram-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/gram-subsect.mldoc

$(PROOF_DIR)/gram.tex:	$(SRC_DIR)/gram.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/gram.mldoc

$(PROOF_DIR)/index.tex:	$(SRC_DIR)/index.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/index.mldoc

$(PROOF_DIR)/lex-subsect.tex:	$(SRC_DIR)/lex-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/lex-subsect.mldoc

$(PROOF_DIR)/lex.tex:	$(SRC_DIR)/lex.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/lex.mldoc

$(PROOF_DIR)/list-aux.tex:	$(SRC_DIR)/list-aux.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/list-aux.mldoc

$(PROOF_DIR)/lp.tex:	$(SRC_DIR)/lp.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/lp.mldoc

$(PROOF_DIR)/messages.tex:	$(SRC_DIR)/messages.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/messages.mldoc

$(PROOF_DIR)/nfa.tex:	$(SRC_DIR)/nfa.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/nfa.mldoc

$(PROOF_DIR)/params.tex:	$(SRC_DIR)/params.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/params.mldoc

$(PROOF_DIR)/pp.tex:	$(SRC_DIR)/pp.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/pp.mldoc

$(PROOF_DIR)/prod-set.tex:	$(SRC_DIR)/prod-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/prod-set.mldoc

$(PROOF_DIR)/prod.tex:	$(SRC_DIR)/prod.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/prod.mldoc

$(PROOF_DIR)/prog-subsect.tex:	$(SRC_DIR)/prog-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/prog-subsect.mldoc

$(PROOF_DIR)/prog.tex:	$(SRC_DIR)/prog.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/prog.mldoc

$(PROOF_DIR)/pt.tex:	$(SRC_DIR)/pt.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/pt.mldoc

$(PROOF_DIR)/reg-fa-subsect.tex:	$(SRC_DIR)/reg-fa-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/reg-fa-subsect.mldoc

$(PROOF_DIR)/reg.tex:	$(SRC_DIR)/reg.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/reg.mldoc

$(PROOF_DIR)/rel.tex:	$(SRC_DIR)/rel.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/rel.mldoc

$(PROOF_DIR)/rfa.tex:	$(SRC_DIR)/rfa.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/rfa.mldoc

$(PROOF_DIR)/set.tex:	$(SRC_DIR)/set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/set.mldoc

$(PROOF_DIR)/sort-set-rel-tab-subsect.tex:	$(SRC_DIR)/sort-set-rel-tab-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/sort-set-rel-tab-subsect.mldoc

$(PROOF_DIR)/sort.tex:	$(SRC_DIR)/sort.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/sort.mldoc

$(PROOF_DIR)/str-set.tex:	$(SRC_DIR)/str-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/str-set.mldoc

$(PROOF_DIR)/str.tex:	$(SRC_DIR)/str.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/str.mldoc

$(PROOF_DIR)/string-aux.tex:	$(SRC_DIR)/string-aux.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/string-aux.mldoc

$(PROOF_DIR)/sym-rel.tex:	$(SRC_DIR)/sym-rel.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/sym-rel.mldoc

$(PROOF_DIR)/sym-set.tex:	$(SRC_DIR)/sym-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/sym-set.mldoc

$(PROOF_DIR)/sym-str-subsect.tex:	$(SRC_DIR)/sym-str-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/sym-str-subsect.mldoc

$(PROOF_DIR)/sym.tex:	$(SRC_DIR)/sym.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/sym.mldoc

$(PROOF_DIR)/system.tex:	$(SRC_DIR)/system.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/system.mldoc

$(PROOF_DIR)/tab.tex:	$(SRC_DIR)/tab.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/tab.mldoc

$(PROOF_DIR)/top-level-subsect.tex:	$(SRC_DIR)/top-level-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/top-level-subsect.mldoc

$(PROOF_DIR)/tran-reg-set.tex:	$(SRC_DIR)/tran-reg-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/tran-reg-set.mldoc

$(PROOF_DIR)/tran-reg.tex:	$(SRC_DIR)/tran-reg.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/tran-reg.mldoc

$(PROOF_DIR)/tran-set.tex:	$(SRC_DIR)/tran-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/tran-set.mldoc

$(PROOF_DIR)/tran.tex:	$(SRC_DIR)/tran.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/tran.mldoc

$(PROOF_DIR)/use.tex:	$(SRC_DIR)/use.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/use.mldoc

$(PROOF_DIR)/utility-subsect.tex:	$(SRC_DIR)/utility-subsect.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/utility-subsect.mldoc

$(PROOF_DIR)/var-set.tex:	$(SRC_DIR)/var-set.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/var-set.mldoc

$(PROOF_DIR)/var.tex:	$(SRC_DIR)/var.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/var.mldoc

$(PROOF_DIR)/version.tex:	$(SRC_DIR)/version.mldoc $(LATEX_INFO)
	$(PROOF_LATEX) $(SRC_DIR)/version.mldoc

clean-info:
	rm -f $(INFO_DIR)/*.info

clean-latex:
	rm -f $(LATEX_FILES)
	rm -f $(LATEX_DIR)/*.aux
	rm -f $(LATEX_DIR)/*.bbl
	rm -f $(LATEX_DIR)/*.blg
	rm -f $(LATEX_DIR)/*.dvi
	rm -f $(LATEX_DIR)/*.idx
	rm -f $(LATEX_DIR)/*.ilg
	rm -f $(LATEX_DIR)/*.ind
	rm -f $(LATEX_DIR)/*.rnd
	rm -f $(LATEX_DIR)/*.nnd
	rm -f $(LATEX_DIR)/*.log
	rm -f $(LATEX_DIR)/*.ps
	rm -f $(LATEX_DIR)/*.pdf
	rm -f $(LATEX_DIR)/*.toc

clean-proof:
	rm -f $(PROOF_FILES)
	rm -f $(PROOF_DIR)/*.aux
	rm -f $(PROOF_DIR)/*.bbl
	rm -f $(PROOF_DIR)/*.blg
	rm -f $(PROOF_DIR)/*.dvi
	rm -f $(PROOF_DIR)/*.idx
	rm -f $(PROOF_DIR)/*.ilg
	rm -f $(PROOF_DIR)/*.ind
	rm -f $(PROOF_DIR)/*.rnd
	rm -f $(PROOF_DIR)/*.nnd
	rm -f $(PROOF_DIR)/*.log
	rm -f $(PROOF_DIR)/*.ps
	rm -f $(PROOF_DIR)/*.pdf
	rm -f $(PROOF_DIR)/*.toc

clean-html:
	rm -f $(HTML_FILES)

clean:	clean-html clean-info clean-latex clean-proof

