(TeX-add-style-hook "chap-3.15"
 (lambda ()
    (LaTeX-add-index-entries
     "finite automaton!design|("
     "finite state system!design|("
     "union@$\\union$"
     "empty-string finite automaton!union@$\\union$"
     "efaToNFA@$\\efaToNFA$"
     "empty-string finite automaton!efaToNFA@$\\efaToNFA$"
     "nondeterministic finite automaton!efaToNFA@$\\efaToNFA$"
     "nfaToDFA@$\\nfaToDFA$"
     "nondeterministic finite automaton!nfaToDFA@$\\nfaToDFA$"
     "deterministic finite automaton!nfaToDFA@$\\nfaToDFA$"
     "minimize@$\\minimize$"
     "deterministic finite automaton!minimize@$\\minimize$"
     "renameStatesCanonically@$\\renameStatesCanonically$"
     "deterministic finite automaton!renameStatesCanonically@$\\renameStatesCanonically$"
     "injDFAToEFA@\\texttt{injDFAToEFA}"
     "EFA@\\texttt{EFA}!union@\\texttt{union}"
     "efaToNFA@\\texttt{efaToNFA}"
     "nfaToDFA@\\texttt{nfaToDFA}"
     "DFA@\\texttt{DFA}!inter@\\texttt{inter}"
     "DFA@\\texttt{DFA}!minimize@\\texttt{minimize}"
     "DFA@\\texttt{DFA}!renameStatesCanonically@\\texttt{renameStatesCanonically}"
     "stuttering"
     "string!stuttering"
     "regToFA@$\\regToFA$"
     "regular expression!regToFA@$\\regToFA$"
     "finite automaton!regToFA@$\\regToFA$"
     "faToEFA@$\\faToEFA$"
     "finite automaton!faToEFA@$\\faToEFA$"
     "empty-string finite automaton!faToEFA@$\\faToEFA$"
     "regToEFA@$\\regToEFA$"
     "regular expression!regToEFA@$\\regToEFA$"
     "empty-string finite automaton!regToEFA@$\\regToEFA$"
     "efaToDFA@$\\efaToDFA$"
     "empty-string finite automaton!efaToDFA@$\\efaToDFA$"
     "deterministic finite automaton!efaToDFA@$\\efaToDFA$"
     "regToDFA@$\\regToDFA$"
     "regular expression!regToDFA@$\\regToDFA$"
     "deterministic finite automaton!regToDFA@$\\regToDFA$"
     "minAndRen@$\\minAndRen$"
     "deterministic finite automaton!minAndRen@$\\minAndRen$"
     "minus@$\\minus$"
     "deterministic finite automaton!minus@$\\minus$"
     "inter@$\\inter$"
     "empty-string finite automaton!inter@$\\inter$"
     "empty-string finite automaton!renameStatesCanonically@$\\renameStatesCanonically$"
     "concat@$\\concat$"
     "empty-string finite automaton!concat@$\\concat$"
     "faToEFA@\\texttt{faToEFA}"
     "regToFA@\\texttt{regToFA}"
     "Reg@\\texttt{Reg}!fromString@\\texttt{fromString}"
     "Reg@\\texttt{Reg}!concat@\\texttt{concat}"
     "Reg@\\texttt{Reg}!power@\\texttt{power}"
     "DFA@\\texttt{DFA}!minus@\\texttt{minus}"
     "EFA@\\texttt{EFA}!concat@\\texttt{concat}"
     "EFA@\\texttt{EFA}!renameStatesCanonically@\\texttt{renameStatesCanonically}"
     "finite state system!synthesis|)"
     "finite automaton!synthesis|)")
    (LaTeX-add-labels
     "ApplicationsOfFiniteAutomataAndRegularExpressions"
     "Stutter1"
     "Stutter2"
     "Stutter3"
     "Stutter4"
     "Stutter5"
     "Stutter6"
     "Stutter7"
     "Stutter8"
     "Stutter9"
     "Stutter10"
     "Stutter11"
     "Stutter12"
     "StuttDFASynExamp")
    (TeX-run-style-hooks
     "chap-3")))

