(TeX-add-style-hook "chap-3.2"
 (lambda ()
    (LaTeX-add-index-entries
     "regular expression|("
     "regular expression!equivalence|("
     " equiv@$\\approx$"
     "regular expression! equiv@$\\approx$"
     "inclusion"
     "set!inclusion"
     "reflexive on set! equiv@$\\approx$"
     "symmetric! equiv@$\\approx$"
     "transitive! equiv@$\\approx$"
     "regular expression! equiv@$\\approx$!reflexive"
     "regular expression! equiv@$\\approx$!symmetric"
     "regular expression! equiv@$\\approx$!transitive"
     "language!concatenation"
     "language!closure"
     "regular expression!equivalence|)"
     "regular expression!design("
     "regular expression!proof of correctness("
     "regular expression!design)"
     "regular expression!proof of correctness)"
     "regular expression)")
    (LaTeX-add-labels
     "EquivalenceOfRegularExpressions"
     "Inclusions"
     "RegEquivalence"
     "RegContext"
     "RegUnion"
     "RegConcat"
     "DistribLan"
     "DistribReg"
     "ClosureInclusions"
     "ClosureLan"
     "ClosureReg"
     "ProvingTheCorrectnessOfRegularExpressions"
     "RegSyn1Lem1"
     "RegSyn1Lem2"
     "RegSyn1Lem3"
     "RegSyn1Lem4"
     "RegSyn1Lem5"
     "RegSyn2Lem1"
     "RegSyn2Lem2"
     "RegSyn2Lem3"
     "RegSyn2Lem5")))

