(TeX-add-style-hook "chap-2.1"
 (lambda ()
    (LaTeX-add-index-entries
     "symbol|("
     "Sym@$\\Sym$"
     "symbol!Sym@$\\Sym$"
     "a, b, c@$a,b,c$"
     "symbol!a, b, c@$a,b,c$"
     "symbol!ordering"
     "countably infinite"
     "symbol|)"
     "string|("
     "list"
     "u, v, w, x, y, z, w@$u, v, w, x, y, z$"
     "string!u, v, w, x, y, z, w@$u, v, w, x, y, z$"
     " percent@$\\%$"
     "string!empty"
     "string! percent@$\\%$"
     "Str@$\\Str$"
     "string!Str@$\\Str$"
     "string!ordering"
     "length!string"
     "string!length"
     " size of@$\\sizedot$"
     "string! size of@$\\sizedot$"
     "string!concatenation"
     "concatenation!string"
     "associative!string concatenation"
     "concatenation!string!associative"
     "string!concatenation!associative"
     "identity!string concatenation"
     "concatenation!string!identity"
     "string!concatenation!identity"
     "string!power"
     "concatenation!string!power"
     "string!concatenation!power"
     " power@$\\cdot^\\cdot$"
     "string! power@$\\cdot^\\cdot$"
     "recursion!natural numbers"
     "mathematical induction"
     "prefix"
     "string!prefix"
     "suffix"
     "string!suffix"
     "substring"
     "string!substring"
     "proper!prefix"
     "proper!suffix"
     "proper!substring"
     "string!prefix!proper"
     "string!suffix!proper"
     "string!substring!proper"
     "prefix!proper"
     "suffix!proper"
     "substring!proper"
     "string|)"
     "alphabet|("
     "alphabet"
     "Sigma@$\\Sigma$"
     "alphabet!Sigma@$\\Sigma$"
     "alphabet@$\\alphabet$"
     "string!alphabet"
     "string!alphabet@$\\alphabet$"
     "recursion!string"
     "recursion!string!right"
     "recursion!string!left"
     " star@$\\cdot^*$"
     "alphabet! star@$\\cdot^*$"
     "alphabet|)"
     "language|("
     "formal language|see{language}"
     "Sigma-language@$\\Sigma$-language"
     "language!Sigma-language@$\\Sigma$-language"
     "palindrome"
     "string!palindrome"
     "countable"
     "Lan@$\\Lan$"
     "language!Lan@$\\Lan$"
     "uncountable"
     "language!alphabet@$\\alphabet$"
     "alphabet!language"
     "language!alphabet"
     "language|)")
    (LaTeX-add-labels
     "SymbolsStringsAlphabetsAndFormalLanguages"
     "StrPowerProp")))

