(TeX-add-style-hook "chap-3.12"
 (lambda ()
    (LaTeX-add-index-entries
     "language!reversal"
     "reversal!language"
     " reversal@$\\cdot^R$"
     "language! reversal@$\\cdot^R$"
     "regular expression!reversal"
     "reversal!regular expression"
     "rev@$\\rev$"
     "regular expression!rev@$\\rev$"
     "finite automaton!reversal"
     "reversal!finite automaton"
     "empty-string finite automaton!reversal"
     "reversal!empty-string finite automaton"
     "finite automaton!rev@$\\rev$"
     "empty-string finite automaton!rev@$\\rev$"
     "language!prefix-closure"
     "language!suffix-closure"
     "language!substring-closure"
     "prefix-closure!language"
     "suffix-closure!language"
     "substring-closure!language"
     "prefix@$\\prefix$"
     "empty-string finite automaton!prefix@$\\prefix$"
     "empty-string finite automaton!prefix-closure"
     "prefix-closure!empty-string finite automaton"
     "nondeterministic finite automaton!prefix@$\\prefix$"
     "nondeterministic finite automaton!prefix-closure"
     "prefix-closure!nondeterministic finite automaton"
     "empty-string finite automaton!suffix@$\\suffix$"
     "empty-string finite automaton!substring@$\\substring$"
     "empty-string finite automaton!suffix-closure"
     "empty-string finite automaton!substring-closure"
     "suffix-closure!empty-string finite automaton"
     "substring-closure!empty-string finite automaton"
     "alphabet renaming!string"
     "string!alphabet renaming"
     " power@$\\cdot^\\cdot$"
     "string! power@$\\cdot^\\cdot$"
     "alphabet renaming!language"
     "language!alphabet renaming"
     "language! power@$\\cdot^\\cdot$"
     "regular expression!alphabet renaming"
     "renameAlphabet@$\\renameAlphabet$"
     "regular expression!renameAlphabet@$\\renameAlphabet$"
     "finite automaton!alphabet renaming"
     "empty-string finite automaton!alphabet renaming"
     "nondeterministic finite automaton!alphabet renaming"
     "deterministic finite automaton!alphabet renaming"
     "finite automaton!renameAlphabet@$\\renameAlphabet$"
     "empty-string finite automaton!renameAlphabet@$\\renameAlphabet$"
     "nondeterministic finite automaton!renameAlphabet@$\\renameAlphabet$"
     "deterministic finite automaton!renameAlphabet@$\\renameAlphabet$"
     "Reg@\\texttt{Reg}!rev@\\texttt{rev}"
     "Reg@\\texttt{Reg}!renameAlphabet@\\texttt{renameAlphabet}"
     "FA@\\texttt{FA}!rev@\\texttt{rev}"
     "prefix@$\\rev$"
     "empty-string finite automaton!rev"
     "EFA@\\texttt{EFA}!rev@\\texttt{rev}"
     "EFA@\\texttt{EFA}!prefix@\\texttt{prefix}"
     "NFA@\\texttt{NFA}!prefix@\\texttt{prefix}"
     "FA@\\texttt{FA}!renameAlphabet@\\texttt{renameAlphabet}"
     "NFA@\\texttt{NFA}!renameAlphabet@\\texttt{renameAlphabet}"
     "DFA@\\texttt{DFA}!renameAlphabet@\\texttt{renameAlphabet}")
    (LaTeX-add-labels
     "ClosurePropertiesOfRegularLanguages"
     "RegularEquiv"
     "DFAMinusTheorem"
     "RegExpRev"
     "FARev"
     "PrefixSuffixSubstringClosure"
     "EFAPrefix"
     "ClosurePropTheorem")
    (TeX-run-style-hooks
     "chap-3")))

