(TeX-add-style-hook "chap-1.2"
 (lambda ()
    (LaTeX-add-index-entries
     "induction|("
     "mathematical induction"
     "induction!mathematical|see{mathematical induction}"
     "inductive hypothesis!mathematical induction"
     "mathematical induction!inductive hypothesis"
     "strong induction"
     "induction!strong|see{strong induction}"
     "inductive hypothesis!strong induction"
     "strong induction!inductive hypothesis"
     "contradiction"
     "relation!well-founded"
     "well-founded relation"
     "relation!well-founded!minimal@$R$-eqtxt{minimal}"
     "well-founded relation!minimal@$R$-eqtxt{minimal}"
     "relation!well-founded!predecessor"
     "well-founded relation!predecessor"
     "predecessor"
     "well-founded induction"
     "induction!well-founded|see{well-founded induction}"
     "inductive hypothesis!well-founded induction"
     "well-founded induction!inductive hypothesis"
     "relation!well-founded!predecessor relation"
     "well-founded relation!predecessor relation"
     "predessor relation"
     "relation!well-founded!predecessor@$\\pred_\\nats$"
     "well-founded relation!predecessor@$\\pred_\\nats$"
     "predecessor@$\\pred_\\nats$"
     "function!inverse image of relation under"
     "function! inverse image of relation under@$\\cdot^{-1}(\\cdot)$"
     " inverse image of relation under@$\\cdot^{-1}(\\cdot)$"
     "relation!well-founded!lexicographic order"
     "well-founded relation!lexicographic order"
     "relation!well-founded!lexicographic@$\\cdot\\lex\\cdot$"
     "well-founded relation!lexicographic@$\\cdot\\lex\\cdot$"
     "induction|)")
    (LaTeX-add-labels
     "Induction"
     "MathIndExamp"
     "NonemptyLeastProp"
     "WellFoundedSubset"
     "InverseImageWellFounded"
     "LexWellFounded")))

