#!/bin/bash

# build Forlan SML/NJ heap image and put in /tmp

# ML-Doc doesn't have to be installed if the src/BASE.sig files are
# newer than the BASE.mldoc files

forlan_version=$(cat ../version.txt)
smlnj_version=$(sml < /dev/null | grep 'Standard ML of New Jersey' | sed -e 's/Standard ML of New Jersey (64-bit) v//' -e 's/ \[built.*//')

echo "Building Heap Image for Forlan Version $version (based on SML/NJ Version $sml_version)"

cd src
change-version $forlan_version $smlnj_version
cleanup

sml <<'END_OF_INPUT'
Control.trackExn := false;
CM.make "forlan.cm";
open TopLevel;
Export.export();
END_OF_INPUT

image=`echo forlan-heap.[a-z][a-z0-9]*-[a-z][a-z0-9]*`
mv $image /tmp
ls -l /tmp/$image
