#!/bin/bash

date=$(date +%Y)

if [ $# != 1 ];
then echo usage $0 PRIMARY.SECONDARY;
     exit 1;
fi;

rm -rf version.sml

sed -e "s/#YEAR#/$date/" -e "s/#VERSION#/$1/" version.sml.template > version.sml

chmod 444 version.sml
