#!/bin/bash

# script for using MLDoc to convert a .mldoc file to a .sig file
# must be run from this directory

base=${1%.mldoc}
echo extracting $base.sig from $1
rm -f $base.sig
cd ../manual
if extract-sig ML-Doc/$1;
then chmod 444 Sigs/$base.sig
     mv Sigs/$base.sig ../src;
else exit 1;
fi;
