#!/bin/bash

rm -rf jforlan/JForlan.app
cp -R ../JForlan.app jforlan
tar cf jforlan.tar jforlan
gzip jforlan.tar
rm -rf jforlan/JForlan.app
mkdir -p ../html/mac
rm -rf ../html/mac/jforlan.tgz
mv jforlan.tar.gz ../html/mac/jforlan.tgz
