#!/bin/bash

# start JForlan

# edit the following line to set appdir to the directory where
# JForlan.app can be found

appdir=/Applications

# suppress start up message ...AdjustCapsLockLEDForKeyTransitionHandling...
exec java -jar $appdir/JForlan.app/Contents/Java/JForlan.jar $* 2> /dev/null
