#!/bin/bash

version=$(cat ../version.txt)
html=$(cat ../html-directory.txt)

echo Installing main WWW pages for Version $version of Forlan in $html

rm -f index.html older-news.html
indextmpfile=/tmp/index-$$
oldertmpfile=/tmp/older-$$
cp index.html.source $indextmpfile
cp older-news.html.source $oldertmpfile
sed "s/#VERSION#/$version/g" $indextmpfile > index.html
sed "s/#VERSION#/$version/g" $oldertmpfile > older-news.html
rm -f $indextmpfile $oldertmpfile

cp style.css $html
mv index.html $html
mv older-news.html $html
cp forlan.bib $html
